import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./styles/index.css";
import Link from "next/link";
import PageLayer from "@/app/PageLayer";
import {Footer} from "@/app/Footer";
import Header from "@/app/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir={"ltr"}>
        <body>
        <Header/>
        <main className={`flex justify-center items-center mx-auto`}>
            <PageLayer>
                {children}
            </PageLayer>
        </main>
        </body>
        </html>
    );
}
