import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./styles/index.css";
import Link from "next/link";
import PageLayer from "@/app/PageLayer";
import {Footer} from "@/app/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir={"ltr"}>
        <body>
        <header className={`bg-white p-8`}>
            <div className={`h-[46vh] flex items-start justify-between gap-14 text-[#251b1b]`}>
                <div className={`flex items-start gap-26`}>
                    <div className={`flex items-start gap-12`}>
                        <div className={``}>
                            <Link className="group flex items-center gap-4" href="/">
                                <div
                                    className="w-10 h-10 border border-primary/50 flex items-center justify-center relative overflow-hidden group-hover:border-accent transition-colors">
                                    <div className="absolute inset-0 bg-primary/10"></div>
                                    <span
                                        className="font-mono text-xs font-bold text-primary group-hover:text-accent">IM</span>
                                </div>
                                <div className="flex flex-col"><span
                                    className="font-display font-bold text-sm tracking-wider uppercase text-foreground">Institutional Mediator</span><span
                                    className="font-mono text-[10px] text-muted-foreground tracking-widest">STRATEGIC RESEARCH NODE</span>
                                </div>
                            </Link>
                        </div>
                        <ul className={`flex flex-col gap-16`}>
                            <li className="text-sm font-mono flex flex-col gap-5 items-start tracking-widest border-l-2 pl-4 transition-all border-transparent text-muted-foreground hover:text-gray-950 hover:border-border"
                            >Team Lending
                                <ul className={`flex flex-col gap-2`}>
                                    <li className={`flex`}>
                                        <Link
                                            className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                            href="/"><span
                                            className="relative z-10">METHODOLOGY</span>
                                            <div
                                                className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                        </Link>
                                    </li>
                                    <li className={`flex`}>
                                        <Link
                                            className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                            href="/"><span
                                            className="relative z-10">METHODOLOGY</span>
                                            <div
                                                className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                        </Link>
                                    </li>
                                </ul>
                                <ul className={`flex flex-col gap-2`}>
                                    <li className="text-sm font-mono flex flex-col gap-5 items-start tracking-widest border-l-2 pl-4 transition-all border-transparent text-muted-foreground hover:text-gray-950 hover:border-border"
                                    >Team Lending
                                        <ul className={`flex flex-col gap-2`}>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                                <ul className={`flex flex-col gap-2`}>
                                    <li className="text-sm font-mono flex flex-col gap-5 items-start tracking-widest border-l-2 pl-4 transition-all border-transparent text-muted-foreground hover:text-gray-950 hover:border-border"
                                    >Team Lending
                                        <ul className={`flex flex-col gap-2`}>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <ul className={`flex flex-col gap-16`}>
                            <li className="text-sm font-mono flex flex-col gap-5 items-start tracking-widest border-l-2 pl-4 transition-all border-transparent text-muted-foreground hover:text-gray-950 hover:border-border"
                            >Team Lending
                                <ul className={`flex flex-col gap-2`}>
                                    <li className={`flex`}>
                                        <Link
                                            className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                            href="/"><span
                                            className="relative z-10">METHODOLOGY</span>
                                            <div
                                                className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                        </Link>
                                    </li>
                                    <li className={`flex`}>
                                        <Link
                                            className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                            href="/"><span
                                            className="relative z-10">METHODOLOGY</span>
                                            <div
                                                className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                        </Link>
                                    </li>
                                </ul>
                                <ul className={`flex flex-col gap-2`}>
                                    <li className="text-sm font-mono flex flex-col gap-5 items-start tracking-widest border-l-2 pl-4 transition-all border-transparent text-muted-foreground hover:text-gray-950 hover:border-border"
                                    >Team Lending
                                        <ul className={`flex flex-col gap-2`}>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                                <ul className={`flex flex-col gap-2`}>
                                    <li className="text-sm font-mono flex flex-col gap-5 items-start tracking-widest border-l-2 pl-4 transition-all border-transparent text-muted-foreground hover:text-gray-950 hover:border-border"
                                    >Team Lending
                                        <ul className={`flex flex-col gap-2`}>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                            <li className={`flex`}>
                                                <Link
                                                    className="relative py-2 text-xs font-mono tracking-widest transition-all group overflow-hidden text-muted-foreground hover:text-gray-600 hover:bg-white/5"
                                                    href="/"><span
                                                    className="relative z-10">METHODOLOGY</span>
                                                    <div
                                                        className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                                                </Link>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div className={`flex flex-col gap-6 w-1/2`}>
                        <h1 className={`text-3xl`}>
                            home page
                        </h1>
                        <p className={`text-justify w-3/4`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores aspernatur atque beatae
                            cumque ducimus enim harum inventore magnam minima nemo nisi odio praesentium quaerat
                            quibusdam quidem rem sed veniam, vitae.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores aspernatur atque beatae
                            cumque ducimus enim harum inventore magnam minima nemo nisi odio praesentium quaerat
                            quibusdam quidem rem sed veniam, vitae.
                        </p>
                    </div>
                </div>
                <div>
                    <Link href={`/`}>
                        mail@us.com
                    </Link>
                </div>
            </div>
        </header>
        <main className={`flex items-center mx-auto`}>
            <PageLayer>
            {children}
            </PageLayer>
        </main>
        <Footer/>

        </body>
        </html>
    );
}
