import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./styles/index.css";
import Link from "next/link";
import PageLayer from "@/app/PageLayer";
import {Footer} from "@/app/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir={"ltr"}>
        <body>
        <header className="relative border-b border-border">

            <div className="max-w-7xl mx-auto px-6 lg:px-12 py-20">

                {/* Top Meta Line */}
                <div className="flex justify-between items-center mb-16">
                    <div className="flex items-center gap-3">
                        <div className="w-2 h-2 bg-primary animate-pulse"></div>
                        <span className="font-mono text-xs text-muted-foreground tracking-widest uppercase">
          Strategic System Online
        </span>
                    </div>

                    <nav
                        className="hidden md:flex gap-10 font-mono text-xs tracking-widest uppercase text-muted-foreground">
                        <Link href="/services" className="hover:text-foreground transition-colors">
                            Services
                        </Link>
                        <Link href="/cases" className="hover:text-foreground transition-colors">
                            Cases
                        </Link>
                        <Link href="/method" className="hover:text-foreground transition-colors">
                            Method
                        </Link>
                        <Link href="/contact" className="hover:text-foreground transition-colors">
                            Contact
                        </Link>
                    </nav>
                </div>

                {/* Structural Title */}
                <div className="max-w-4xl">
                    <h1 className="font-display text-4xl md:text-6xl tracking-tight leading-tight mb-8">
                        Product, Revenue & Organizational Architecture
                        <span className="block text-muted-foreground text-2xl md:text-3xl mt-4">
          for Software Companies Scaling in Competitive Markets
        </span>
                    </h1>

                    <p className="text-muted-foreground text-base leading-relaxed max-w-2xl">
                        We design structural alignment across product positioning, revenue systems,
                        and institutional decision flows. Built for founder-led and growth-stage SaaS.
                    </p>

                    <div className="mt-12 flex gap-8 font-mono text-xs tracking-widest uppercase">
                        <Link
                            href="/contact"
                            className="border-b border-primary text-primary pb-1 hover:opacity-80 transition"
                        >
                            Request Diagnostic
                        </Link>

                        <Link
                            href="/cases"
                            className="border-b border-border pb-1 hover:border-foreground transition"
                        >
                            View Results
                        </Link>
                    </div>
                </div>

            </div>

            {/* Vertical structural lines to match PageLayer */}
            <div className="absolute top-0 left-12 w-[1px] h-full bg-border pointer-events-none"/>
            <div className="absolute top-0 right-12 w-[1px] h-full bg-border pointer-events-none"/>

        </header>
        <main className={`flex justify-center items-center mx-auto`}>
            <PageLayer>
                {children}
            </PageLayer>
        </main>
        </body>
        </html>
    );
}
